server:
  port: 8080


quanyu:
  ai:
    # 策略: openai / ollama
    strategy: ollama
    config:
      # deepseek API示例
#      chat-url: https://api.deepseek.com/chat/completions
#      api-key: <你的api key>
#      model: deepseek-chat
      # qwen3 API示例
#      chat-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
#      api-key: <你的api key>
#      model: qwen3-235b-a22b
      # ollama示例
      chat-url: http://localhost:11434/api/chat
      model: qwen3:8b